### ISSUE TITLE
Logs are created in a "venv" folder

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/cloudshell-logging#2]
Using cloudshell-orch-core with cloudshell-logging, sandbox logs folder is created, but a subfolder called venv is created as well. This is a new behavior that didn't exist in cloudshell-core.

cloudshell-logging
![image](https://user-images.githubusercontent.com/12639815/53692229-ee102380-3d94-11e9-83fe-c535fbf2ffc2.png)

cloudshell-core
![image](https://user-images.githubusercontent.com/12639815/53692238-041de400-3d95-11e9-8976-300fcd23973e.png)

**Comment by TomerAdmon** [comment]
@yaroslavNqualisystems  - this issue can be updated to resolved, right?

**Comment by Costya-Y** [comment]
Hi @TomerAdmon 

Yes, you are correct. Issue resolved. Closing it.
